spring:
  application:
    name: delivery
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 7771
  error:
    include-message: always
